apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xclusters.gcp.projectx.mavenwave.dev
spec:
  group: gcp.projectx.mavenwave.dev
  names:
    kind: XCluster
    plural: xclusters
  claimNames:
    kind: Cluster
    plural: clusters
  connectionSecretKeys:
  - kubeconfig
  defaultCompositionRef:
    name: projectx-gcp-gke-cluster
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  providerConfigRef:
                    type: object
                    properties:
                      name:
                        type: string
                        description: Provider config for resources
                    required:
                    - name
                  id:
                    type: string
                    description: Referenceable id for resources
                  authorizedNetworks:
                    type: object
                    properties:
                      enabled:
                        type: boolean
                        default: false
                      cidrBlocks:
                        type: array
                        items:
                          type: object
                          properties:
                            displayName:
                              type: string
                            cidrBlock:
                              type: string
                  databaseEncryption:
                    type: object
                    properties:
                      state:
                        type: string
                        description: State of etcd encryption
                        default: "DECRYPTED"
                      keyName:
                        type: string
                        description: Name of CloudKMS key
                  network:
                    type: object
                    properties:
                      id:
                        type: string
                        description: ID of VPC to attach
                    required:
                    - id
                  masterIpv4CidrBlock:
                    type: string
                    default: 172.16.0.0/28
                  projectId:
                      type: string
                      description: Google project ID
                  region:
                    type: string
                    enum:
                    - us-central
                    - us-east
                    - us-west
                    default: us-central
                    description: Cluster region
                required:
                - providerConfigRef
                - id
                - projectId
            required:
            - parameters
                  
          status:
            type: object
            properties:
              selfLink:
                type: string
                description: Cluster selflink
              endpoint:
                type: string
                description: Cluster endpoint
              podIpv4Cidr:
                type: string
                description: Cluster pods cidr
              servicesIpv4Cidr:
                type: string
                description: Cluster services cidr
              location:
                type: string
                description: Cluster location