---
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: kubernetes-provider
spec:
  serviceAccountName: kubernetes-provider
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: crossplane-provider-helm
spec:
  # package: crossplane/provider-helm:v0.10.0
  package: us.gcr.io/bradw-nextgen-devops/provider-helm-amd64:v0.11.0-rc.18.g3fe27ae
  controllerConfigRef:
    name: kubernetes-provider