---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubernetes-provider
  namespace: crossplane-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crossplane-provider-rb
subjects:
- kind: ServiceAccount
  name: kubernetes-provider
  namespace: crossplane-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io