apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: projectx-services-crossplane
  labels:
    crossplane.io/xrd: xcrossplane.services.projectx.mavenwave.dev
spec:
  compositeTypeRef:
    apiVersion: services.projectx.mavenwave.dev/v1alpha1
    kind: XCrossplane
  writeConnectionSecretsToNamespace: crossplane-system
  patchSets:
  - name: common
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: metadata.labels
    - type: FromCompositeFieldPath
      fromFieldPath: spec.claimRef.namespace
      toFieldPath: metadata.labels[ref.projectx.mavenwave.dev/tenant]
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.providerConfigRef.name
      toFieldPath: spec.providerConfigRef.name
  resources:
  # Helm Chart
  - name: crossplane
    base:
      apiVersion: helm.crossplane.io/v1beta1
      kind: Release
      metadata:
        annotations: 
          crossplane.io/external-name: crossplane
      spec:
        forProvider:
          chart:
            name: crossplane
            repository: https://charts.crossplane.io/stable/
            version: 1.8.1
          namespace: crossplane-system
          wait: true
        rollbackLimit: 5
    patches:
    - type: PatchSet
      patchSetName: common
    - type: CombineFromComposite
      combine:
        variables:
        - fromFieldPath: spec.claimRef.namespace
        - fromFieldPath: spec.claimRef.name
        strategy: string
        string:
          fmt: "%s-%s-crossplane"
      toFieldPath: metadata.name