apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xcrossplane.services.projectx.mavenwave.dev
spec:
  group: services.projectx.mavenwave.dev
  names:
    kind: XCrossplane
    plural: xcrossplane
  claimNames:
    kind: Crossplane
    plural: crossplane
  defaultCompositionRef:
    name: projectx-services-crossplane
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  providerConfigRef:
                    type: object
                    properties:
                      name:
                        type: string
                    required:
                    - name
                required:
                - providerConfigRef
            required:
            - parameters
                  
          status:
            type: object
            properties: