---
apiVersion: gcp.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: example
  namespace: crossplane-system
spec:
  projectID:
  credentials:
    source: Secret
    secretRef:
      key: credentials
      name: gcp-default
      namespace: example
