---
apiVersion: helm.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: example
  namespace: crossplane-system
spec:
  credentials:
    source: Secret
    secretRef:
      key: credentials
      name: k8s-default
      namespace: example

