apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: projectx-platform-tenant-gcp
  labels:
    crossplane.io/xrd: tenants.platform.projectx.mavenwave.dev
    provider: gcp
spec:
  compositeTypeRef:
    apiVersion: platform.projectx.mavenwave.dev/v1alpha1
    kind: Tenant
  writeConnectionSecretsToNamespace: crossplane-system
  patchSets:
  - name: common
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: metadata.name
      toFieldPath: metadata.labels[ref.projectx.mavenwave.dev/team]
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.providerConfigRef.name
      toFieldPath: spec.providerConfigRef.name
  resources:
# GCP Project
  - name: project
    base:
      apiVersion: cloudplatform.gcp.jet.crossplane.io/v1alpha2
      kind: Project
      spec:
        forProvider:
          autoCreateNetwork: false
          skipDelete: true
    patches:
    - type: PatchSet
      patchSetName: common
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.google.project.billingAccount
      toFieldPath: spec.forProvider.billingAccount
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.google.project.folderId
      toFieldPath: spec.forProvider.folderId
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.google.project.labels
      toFieldPath: spec.forProvider.labels
    - type: FromCompositeFieldPath
      fromFieldPath: metadata.name
      toFieldPath: spec.forProvider.name
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.google.project.orgId
      toFieldPath: spec.forProvider.orgId
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.google.project.projectId
      toFieldPath: spec.forProvider.projectId
