apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: tenants.platform.projectx.mavenwave.dev
spec:
  group: platform.projectx.mavenwave.dev
  names:
    kind: Tenant
    plural: tenants
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            required:
            - parameters
            properties:
              parameters:
                type: object
                required:
                - providerConfigRef
                properties:
                  providerConfigRef:
                    type: object
                    properties:
                      name:
                        type: string
                    required:
                    - name
                  google:
                    type: object
                    required:
                    - project
                    properties:
                      project:
                        type: object
                        required:
                        - projectId
                        properties:
                          projectId:
                            type: string
                          billingAccount:
                            type: string
                          folderId:
                            type: string
                          labels:
                            type: object
                            additionalProperties:
                              type: string
                          orgId:
                            type: string
          status:
            type: object
            properties: