apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: databases.platform.projectx.mavenwave.dev

spec:
  group: platform.projectx.mavenwave.dev
  names: 
    kind: Database
    plural: Databases
  claimNames:
    kind: DatabaseClaim
    plural: databaseclaims
  connectionSecretKeys:
  - kubeconfig
  defaultCompositionRef:
    name: gcp-standard-projectx-database
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec: 
            type: object
            properties:
              parameters:
                type: object
                properties:
                  privateNetwork:
                    type: string
                    description: Network that has VPC_PEERING enabled
                required:
                - privateNetwork
            required:
            - parameters

        status:
          type: object
          properties:
            address:
              description: Address of this PostgreSQL server
              type: string
              conditions:
                type: array
                items:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true

            crossplane:
              type: object
              properties:
                conditions:
                  type: array
                  items:
                    type: object
                    x-kubernetes-preserve-unknown-fields: true
                google:
                  type: object
                  properties:
