apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: gcp-standard-database-platform-projectx
  labels:
    crossplane.io/xrd: databases.platform.projectx.mavenwave.dev
    provider: gcp
    class: standard

spec:
  compositeTypeRef:
    apiVersion: platform.projectx.mavenwave.dev/v1alpha1
    kind: Database
  writeConnectionSecretsToNamespace: crossplane-system
  patchSets:
    - name: providerConfig
      patches:
      - type: FromCompositeFieldPath
        fromFieldPath: spec.claimRef.namespace
        toFieldPath: spec.providerConfigRef.name
  resources:
    - name: PrivateIPAddress
      base:
        apiVersion: compute.gcp.crossplane.io/v1beta1
        kind: GlobalAddress
        spec:
          forProvider:
            addressType: INTERNAL
            prefixLength: 16
            purpose: VPC_PEERING
      patches:
        - fromFieldPath: spec.parameters.networkRef.name
          toFieldPath: spec.forProvider.networkRef.name
        - toFieldPath: status.atProvider.id
          fromFieldPath: status.GlobalAddress.id
        - toFieldPath: status.atProvider.conditions.status
          fromFieldPath: status.GlobalAddress.conditions[0].status
        - type: PatchSet
          patchSetName: providerConfig

    - name: PrivateConnection
      base:
        apiVersion: servicenetworking.gcp.crossplane.io/v1beta1
        kind: Connection
        spec:
          forProvider:
            parent: services/servicenetworking.googleapis.com
            reservedPeeringRangesSelector:
              matchControllerRef: true
            service: servicenetworking.googleapis.com
      patches:
        - fromFieldPath: spec.parameters.networkRef.name
          toFieldPath: spec.forProvider.networkRef.name
        - type: PatchSet
          patchSetName: providerConfig

    - name: DBInstance
      base:
        apiVersion: database.gcp.crossplane.io/v1beta1
        kind: CloudSQLInstance
        spec:
          forProvider:
            databaseVersion: POSTGRES_13
            deletionProtection: false
            region: us-central1
            settings:
              dataDiskSizeGb: 20
              tier: db-f1-micro
              ipConfiguration:
                ipv4Enabled: false
      patches:
        - fromFieldPath: metadata.uid
          toFieldPath: spec.writeConnectionSecretToRef.name
          transforms:
            - type: string
              string:
                fmt: "%s-gcp-postgresql"
        - fromFieldPath: spec.writeConnectionSecretToRef.namespace
          toFieldPath: spec.writeConnectionSecretToRef.namespace
        - fromFieldPath: spec.parameters.storageGB
          toFieldPath: spec.forProvider.settings.dataDiskSizeGb
        - fromFieldPath: spec.parameters.network
          toFieldPath: spec.forProvider.settings.ipConfiguration.privateNetwork
        - type: PatchSet
          patchSetName: providerConfig

      connectionDetails:
      - name: kubeconfig
        fromConnectionSecretKey: kubeconfig
