apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: gcp-standard-projectx-platform-database
  labels:
    crossplane.io/xrd: databases.platform.projectx.mavenwave.dev
    provider: gcp
    class: standard

spec:
  compositeTypeRef:
    apiVersion: platofom.projectx.mavenwave.dev
    kind: Database
  writeConnectionSecretsToNamespace: crossplane-system
  resources:
  - name: cloudsqlinstance
    base:
      apiVersion: database.gcp.crossplane.io/v1beta1
      kind: CloudSQLInstance
      spec:
        forProvider:
          databaseVersion: POSTGRES_13
          region: us-central1
          settings:
            tier: db-custom-1-3840
            ipConfiguration:
              ipv4Enabled: true
              
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.size
      toFieldPath: spec.forProvider.settings.tier
      policy:
        fromFieldPath: Required
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.ipConfiguration
      toFieldPath: spec.forProvider.settings.ipConfiguration.privateNetwork
      policy:
        fromFieldPath: Required
    
    connectionDetails:
    - name: kubeconfig
      fromConnectionSecretKey: kubeconfig
    readinessChecks:
    - type: MatchString
      fieldPath: "status.atProvider.status"
      matchString: "RUNNING"

