apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xnodepools.gcp.projectx.mavenwave.dev
spec:
  group: gcp.projectx.mavenwave.dev
  names:
    kind: XNodePool
    plural: xnodepools
  claimNames:
    kind: NodePool
    plural: nodepools
  defaultCompositionRef:
    name: projectx-gcp-gke-nodepool
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  providerConfigRef:
                    type: object
                    properties:
                      name:
                        type: string
                        description: Provider config for resources
                    required:
                    - name
                  id:
                    type: string
                    description: Referenceable id for resources
                  cluster:
                    type: object
                    properties:
                      id:
                        type: string
                    required:
                    - id
                  machineType:
                    type: string
                    enum:
                    - small
                    - medium
                    description: Node pool machine type
                    default: small
                  min:
                    type: integer
                    description: Minimum number of cluster nodes
                    default: 1
                  max:
                    type: integer
                    description: Maximum number of cluster nodes
                    default: 10
                  tags:
                    type: array
                    description: Node pool network tags
                    default: []
                    items:
                      type: string
                required:
                - providerConfigRef
                - id
                - cluster
            required:
            - parameters
                  
          status:
            type: object
            properties:
              selfLink:
                type: string
                description: Node pool selflink