apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/kind/deploy.yaml

patchesJson6902:
- target:
    version: v1
    kind: Deployment
    name: ingress-nginx-controller
  path: add-args.yaml