- op: add
  path: /spec/resources/-1
  value:
    name: crossplane
    base:
      apiVersion: helm.crossplane.io/v1beta1
      kind: Release
      metadata:
        annotations: 
          crossplane.io/external-name: crossplane
      spec:
        forProvider:
          chart:
            name: crossplane
            repository: https://charts.crossplane.io/stable/
            version: 1.9.0
          namespace: crossplane-system
          wait: true
        rollbackLimit: 5
    patches:
    - type: PatchSet
      patchSetName: metadata
    - type: CombineFromComposite
      combine:
        variables:
        - fromFieldPath: spec.claimRef.namespace
        - fromFieldPath: spec.claimRef.name
        strategy: string
        string:
          fmt: "%s-%s"
      toFieldPath: metadata.name
    - type: CombineFromComposite
      combine:
        variables:
        - fromFieldPath: spec.claimRef.namespace
        - fromFieldPath: spec.claimRef.name
        strategy: string
        string:
          fmt: "%s-%s"
      toFieldPath: spec.providerConfigRef.name
    - type: ToCompositeFieldPath
      fromFieldPath: status.conditions
      toFieldPath: status.crossplane.conditions

- op: add
  path: /spec/resources/-1
  value:
    name: crossplane-platform-config
    base:
      apiVersion: kubernetes.crossplane.io/v1alpha1
      kind: Object
      spec:
        forProvider:
          manifest:
            apiVersion: pkg.crossplane.io/v1
            kind: Configuration
            metadata:
              name: platform
            spec:
              package: ghcr.io/mavenwave-devops/projectx-crossplane-platform:main
              packagePullPolicy: Always
              skipDependencyResolution: true
    patches:
    - type: PatchSet
      patchSetName: metadata
    - type: CombineFromComposite
      combine:
        variables:
        - fromFieldPath: spec.claimRef.namespace
        - fromFieldPath: spec.claimRef.name
        strategy: string
        string:
          fmt: "%s-%s-crossplane-platform-config"
      toFieldPath: metadata.name
    - type: CombineFromComposite
      combine:
        variables:
        - fromFieldPath: spec.claimRef.namespace
        - fromFieldPath: spec.claimRef.name
        strategy: string
        string:
          fmt: "%s-%s"
      toFieldPath: spec.providerConfigRef.name
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.platform.version
      toFieldPath: spec.forProvider.manifest.spec.package
      transforms:
      - type: string
        string:
          fmt: "ghcr.io/mavenwave-devops/projectx-crossplane-platform:%s"