---
apiVersion: gcp.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: walker
  namespace: crossplane-system
spec:
  projectID: ignite-walker-project-gbt
  credentials:
    source: Secret
    secretRef:
      key: credentials
      name: gcp-default
      namespace: crossplane-system
