---
apiVersion: gcp.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
  namespace: crossplane-system
spec:
  projectID: wise-vim-352714
  credentials:
    source: Secret
    secretRef:
      key: credentials
      name: gcp-default
      namespace: crossplane-system
