apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: crossplane-system

resources:
- provider.yaml

configMapGenerator:
- name: provider
  env: config.properties

replacements:
- source:
    kind: ConfigMap
    name: provider
    fieldPath: data.PROJECTID
  targets:
  - select:
      kind: ProviderConfig
    fieldPaths:
    - spec.projectID