---
apiVersion: gcp.jet.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: default
  namespace: crossplane-system
spec:
  projectID: 
  credentials:
    source: Secret
    secretRef:
      key: credentials
      name: gcp-default
      namespace: crossplane-system