apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: clusters.platform.tidalwave.mavenwave.dev
spec:
  group: platform.tidalwave.mavenwave.dev
  names:
    kind: Cluster
    plural: clusters
  claimNames:
    kind: ClusterClaim
    plural: clusterclaims
  connectionSecretKeys:
  - kubeconfig
  defaultCompositionRef:
    name: gcp-simple-cluster-platform-tidalwave
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            required:
            - parameters
            properties:
              parameters:
                type: object
                required: []
                default: {}
                properties:
                  region:
                    type: string
                    enum:
                    - us-central-zone
                    - us-central
                    - us-east
                    - us-west
                    default: us-central-zone
                    description: Resources region
                  networkId:
                    type: string
                    description: Select network with label platform.tidalwave.mavenwave.dev/network-id
                    default: default
                  controlPlaneIpv4CidrBlock:
                    type: string
                    description: The IP range in CIDR notation to use for the hosted master network
                    default: 172.16.0.0/28
                  nodeCidr:
                    type: string
                    description: Nodes subnet CIDR
                    default: 10.0.0.0/24
                  podCidr:
                    type: string
                    description: Pods subnet CIDR
                    default: 10.1.0.0/16
                  serviceCidr:
                    type: string
                    description: Services subnet CIDR
                    default: 10.2.0.0/20
                  authorizedNetworks:
                    type: object
                    description: The configuration options for master authorized networks feature
                    default: {}
                    properties:
                      enabled:
                        type: boolean
                        description: Whether or not master authorized networks is enabled
                        default: false
                      cidrBlocks:
                        type: array
                        items:
                          type: object
                          properties:
                            displayName:
                              type: string
                              description: An optional field for users to identify CIDR blocks
                            cidrBlock:
                              type: string
                              description: Must be specified in CIDR notation
                  diskSizeGb:
                    type: integer
                    description: Node disk size in GB
                    default: 50
                  preemptible:
                    type: boolean
                    default: false
                  identity:
                    type: object
                    required: []
                    default: {}
                    properties:
                      source:
                        type: string
                        default: Secret
                      secretRefName:
                        type: string
                        default: default
                      secretRefKey: 
                        type: string
                        default: credentials
                  nodeMachineType:
                    type: string
                    enum:
                    - small
                    - medium
                    description: Node pool machine type
                    default: small
                  nodeMin:
                    type: integer
                    description: Minimum number of cluster nodes
                    default: 1
                  nodeMax:
                    type: integer
                    description: Maximum number of cluster nodes
                    default: 10
                  google:
                    type: object
                    required: []
                    default: {}
                    properties:
                      project:
                        type: object
                        required:
                        - number
                        - id
                        properties:
                          number:
                            type: string
                          id:
                            type: string
          status:
            type: object
            properties:
              network:
                type: object
                properties:
                  clusterEgressFw:
                    type: object
                    properties:
                      conditions:
                        type: array
                        items:
                          type: object
                          x-kubernetes-preserve-unknown-fields: true
                  webhooksFw:
                    type: object
                    properties:
                      conditions:
                        type: array
                        items:
                          type: object
                          x-kubernetes-preserve-unknown-fields: true
                  router:
                    type: object
                    properties:
                      conditions:
                        type: array
                        items:
                          type: object
                          x-kubernetes-preserve-unknown-fields: true
              kms:
                type: object
                properties:
                  keyRing:
                    type: object
                    properties:
                      name:
                        type: string
                      conditions:
                        type: array
                        items:
                          type: object
                          x-kubernetes-preserve-unknown-fields: true
                  cryptoKey:
                    type: object
                    properties:
                      name:
                        type: string
                      conditions:
                        type: array
                        items:
                          type: object
                          x-kubernetes-preserve-unknown-fields: true
                  cryptoKeyPolicy:
                    type: object
                    properties:
                      conditions:
                        type: array
                        items:
                          type: object
                          x-kubernetes-preserve-unknown-fields: true
              cluster:
                type: object
                properties:
                  conditions:
                    type: array
                    items:
                      type: object
                      x-kubernetes-preserve-unknown-fields: true
                  name:
                    type: string
                  endpoint:
                    type: string
                  selfLink:
                    type: string
                  location:
                    type: string
                  pods:
                    type: object
                    properties:
                      cidr:
                        type: string
                  services:
                    type: object
                    properties:
                      cidr:
                        type: string
              nodePool:
                type: object
                properties:
                  conditions:
                    type: array
                    items:
                      type: object
                      x-kubernetes-preserve-unknown-fields: true
                  selfLink:
                    type: string