---
apiVersion: gcp.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: default #use the same name as the namespace that you are using
  namespace: crossplane-system
spec:
  projectID: 
  credentials:
    source: Secret
    secretRef:
      key: token
      name: 
      namespace: 