apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xvcluster.services.projectx.mavenwave.dev
spec:
  group: services.projectx.mavenwave.dev
  names:
    kind: XVcluster
    plural: xvcluster
  claimNames:
    kind: Vcluster
    plural: vcluster
  defaultCompositionRef:
    name: projectx-services-vcluster
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  providerConfigRef:
                    type: object
                    properties:
                      name:
                        type: string
                    required:
                    - name
                  domain:
                    type: string
                  port:
                    type: integer
                    default: 443
                  values:
                    type: object
                    x-kubernetes-preserve-unknown-fields: true
                required:
                - providerConfigRef
                - domain
            required:
            - parameters
                  
          status:
            type: object
            properties: