---
apiVersion: platform.projectx.mavenwave.dev/v1alpha1
kind: ClusterClaim
metadata:
  name: dev
spec:
  compositionSelector:
    matchLabels:
      provider: gcp
      class: standard
  writeConnectionSecretToRef:
    name: a-team-dev
  parameters:
    google:
      project:
        id: bradw-nextgen-devops
        number: "809429613600"
    identity: {}
    # network:
    #   nodes:
    #     cidr: 10.0.0.0/24
    #   pods:
    #     cidr: 10.1.0.0/16
    #   services:
    #     cidr: 10.2.0.0/20
    # cluster: {}
    #   identity:
    #     source: Secret
    #     secretRef:
    #       name: gcp-default