---
apiVersion: platform.tidalwave.mavenwave.dev/v1alpha1
kind: ClusterClaim
metadata:
  name: example
spec:
  compositionSelector:
    matchLabels:
      provider: gcp
      class: simple
  writeConnectionSecretToRef:
    name: dev-cluster
  parameters:
    nodeMachineType: medium
    google:
      project:
        id: bradw-nextgen-devops
        number: "809429613600"
    identity:
      secretRefName: gcp-default
    # network:
    #   nodes:
    #     cidr: 10.0.0.0/24
    #   pods:
    #     cidr: 10.1.0.0/16
    #   services:
    #     cidr: 10.2.0.0/20
    # cluster: {}
    #   identity:
    #     source: Secret
    #     secretRef:
    #       name: gcp-default