---
apiVersion: platform.projectx.mavenwave.dev/v1alpha1
kind: ControlPlaneClaim
metadata:
  name: controlplane
  namespace: b-team
spec:
  compositionSelector:
    matchLabels:
      provider: gcp
  writeConnectionSecretToRef:
    name: b-team-controlplane
  parameters:
    platform:
      version: latest
    google:
      project:
        id: bradw-nextgen-devops
        number: "809429613600"
      network:
        nodes:
          cidr: 10.10.0.0/24
        pods:
          cidr: 10.11.0.0/16
        services:
          cidr: 10.12.0.0/20
      cluster:
        identity:
          secretRef: {}
      crossplane:
        serviceAccount:
          email: crossplane@bradw-nextgen-devops.iam.gserviceaccount.com