apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patchesJson6902:
- target:
    group: apiextensions.crossplane.io
    version: v1
    kind: Composition
    name: projectx-platform-controlplane
  path: firewall.yaml