---
apiVersion: k3d.io/v1alpha2
kind: Simple
name: k3s-default
servers: 1
agents: 1
image: docker.io/rancher/k3s:latest
ports:
- port: 8080:80 # same as `--port '8080:80@loadbalancer'`
  nodeFilters:
  - loadbalancer
- port: 4430:443 # same as `--port '4430:443@loadbalancer'`
  nodeFilters:
  - loadbalancer
