apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: projectx-platform-controlplane-vcluster
  labels:
    crossplane.io/xrd: controlplanes.platform.projectx.mavenwave.dev
    provider: vcluster
spec:
  compositeTypeRef:
    apiVersion: platform.projectx.mavenwave.dev/v1alpha1
    kind: ControlPlane
  writeConnectionSecretsToNamespace: crossplane-system
  patchSets:
  - name: common
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: metadata.name
      toFieldPath: metadata.labels[ref.projectx.mavenwave.dev/controlplane]
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.providerConfigRef.name
      toFieldPath: spec.providerConfigRef.name
  resources:
# Vcluster
  - name: vcluster
    base:
      apiVersion: helm.crossplane.io/v1beta1
      kind: Release
      spec:
        forProvider:
          chart:
            name: vcluster
            repository: https://charts.loft.sh
            version: 0.11.0-alpha.0
          wait: true
          set:
          - name: ingress.enabled
            value: "true"
          - name: ingress.host
          - name: syncer.extraArgs[0]
          - name: syncer.extraArgs[1]
        rollbackLimit: 5
    patches:
    - type: PatchSet
      patchSetName: common
    - type: FromCompositeFieldPath
      fromFieldPath: metadata.name
      toFieldPath: metadata.annotations[crossplane.io/external-name]
      transforms:
      - type: string
        string:
          fmt: "%s-vcluster"
    - type: FromCompositeFieldPath
      fromFieldPath: metadata.name
      toFieldPath: metadata.name
      transforms:
      - type: string
        string:
          fmt: "%s-vcluster"
    - type: FromCompositeFieldPath
      fromFieldPath: metadata.name
      toFieldPath: spec.forProvider.namespace
    - type: CombineFromComposite
      combine:
        variables:
        - fromFieldPath: metadata.name
        - fromFieldPath: spec.parameters.domain
        strategy: string
        string:
          fmt: "%s.%s"
      toFieldPath: spec.forProvider.set[1].value
    - type: CombineFromComposite
      combine:
        variables:
        - fromFieldPath: metadata.name
        - fromFieldPath: spec.parameters.domain
        - fromFieldPath: spec.parameters.port
        strategy: string
        string:
          fmt: "--out-kube-config-server=https://%s.%s:%d"
      toFieldPath: spec.forProvider.set[2].value
    - type: FromCompositeFieldPath
      fromFieldPath: metadata.name
      toFieldPath: spec.forProvider.set[3].value
      transforms:
      - type: string
        string: 
          fmt: "--out-kube-config-secret=%s-kubeconfig"