apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: controlplanes.platform.projectx.mavenwave.dev
spec:
  group: platform.projectx.mavenwave.dev
  names:
    kind: ControlPlane
    plural: controlplanes
  connectionSecretKeys:
  - kubeconfig
  defaultCompositionRef:
    name: projectx-platform-controlplane-vcluster-gcp
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            required:
            - parameters
            properties:
              parameters:
                type: object
                required:
                - domain
                properties:
                  region:
                    type: string
                    enum:
                    - us-central
                    - us-east
                    - us-west
                    default: us-central
                    description: Resources region
                  vcluster:
                    type: object
                    properties:
                      domain:
                        type: string
                      port:
                        type: integer
                        default: 443
                      platform:
                        type: object
                        properties:
                          versions:
                            type: string
                            default: main
                  google:
                    type: object
                    properties:
                      network:
                        type: object
                        properties:
                          nodes:
                            type: object
                            properties:
                              cidr:
                                type: string
                                description: Nodes subnet CIDR
                              tags:
                                type: array
                                description: Node pool network tags
                                default: []
                                items:
                                  type: string
                      cluster:
                        type: object
                        properties:
                          masterIpv4CidrBlock:
                            type: string
                            description: The IP range in CIDR notation to use for the hosted master network
                            default: 172.16.0.0/28
          status:
            type: object
            properties:
              network:
                type: object
                properties:
                  id:
                    type: string
                  selfLink:
                    type: string
              kms:
                type: object
                properties:
                  keyRing:
                    type: object
                    properties:
                      name:
                        type: string