apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: controlplanes.platform.projectx.mavenwave.dev
spec:
  group: platform.projectx.mavenwave.dev
  names:
    kind: ControlPlane
    plural: controlplanes
  defaultCompositionRef:
    name: projectx-platform-controlplane-vcluster-gcp
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            required:
            - parameters
            properties:
              parameters:
                type: object
                required:
                - domain
                properties:
                  domain:
                    type: string
                  port:
                    type: integer
                    default: 443
                  platform:
                    type: object
                    properties:
                      versions:
                        type: string
                        default: main
          status:
            type: object
            properties: