apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: clusters.gcp.projectx.mavenwave.dev
spec:
  group: platform.projectx.mavenwave.dev
  names:
    kind: Cluster
    plural: clusters
  claimNames:
    kind: ClusterClaim
    plural: clusterclaims
  defaultCompositionRef:
    name: projectx-gcp-gke-minimal
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  gcp:
                    type: object
                    properties:
                      projectId:
                        type: string
                        description: Google project ID
                      projectNumber:
                        type: string
                        description: Google project number
                    required:
                    - projectId
                    - projectNumber
                  region:
                    type: string
                    enum:
                    - us-central
                    - us-east
                    - us-west
                    default: us-central
                    description: Resources region
                  network:
                    type: object
                    description: GKE cluster network
                    properties:
                      nodes:
                        type: object
                        properties:
                          cidr:
                            type: string
                            description: Nodes subnet CIDR
                          tags:
                            type: array
                            description: Node pool network tags
                            default: []
                            items:
                              type: string
                        required:
                        - cidr
                        - tags
                      pods:
                        type: object
                        properties:
                          cidr:
                            type: string
                            description: Pods subnet CIDR
                        required:
                        - cidr
                      services:
                        type: object
                        properties:
                          cidr:
                            type: string
                            description: Services subnet CIDR
                        required:
                        - cidr
                    required:
                    - nodes
                    - pods
                    - services
                  cluster:
                    type: object
                    description: GKE cluster settings
                    properties:
                      identity:
                        type: object
                        properties:
                          source:
                            type: string
                            default: InjectedIdentity
                      authorizedNetworks:
                        type: object
                        description: The configuration options for master authorized networks feature
                        properties:
                          enabled:
                            type: boolean
                            description: Whether or not master authorized networks is enabled
                            default: false
                          cidrBlocks:
                            type: array
                            items:
                              type: object
                              properties:
                                displayName:
                                  type: string
                                  description: An optional field for users to identify CIDR blocks
                                cidrBlock:
                                  type: string
                                  description: Must be specified in CIDR notation
                      diskSizeGb:
                        type: integer
                        description: Node disk size in GB
                        default: 50
                      masterIpv4CidrBlock:
                        type: string
                        description: The IP range in CIDR notation to use for the hosted master network
                        default: 172.16.0.0/28
                      machineType:
                        type: string
                        enum:
                        - small
                        - medium
                        description: Node pool machine type
                        default: small
                      min:
                        type: integer
                        description: Minimum number of cluster nodes
                        default: 1
                      max:
                        type: integer
                        description: Maximum number of cluster nodes
                        default: 10
                    required:
                    - identity
                required:
                - gcp
                - network
                - cluster
            required:
            - parameters
                  
          status:
            type: object
            properties:
              network:
                type: object
                properties:
                  id:
                    type: integer
                    description: Network ID
                  selfLink:
                    type: string
                    description: Network self link
              kms:
                type: object
                properties:
                  keyRing:
                    type: object
                    properties:
                      name:
                        type: string
                        description: Name of KMS keyring
                  cryptoKey:
                    type: object
                    properties:
                      name:
                        type: string
                        description: Name of KMS crypto key
              cluster:
                type: object
                properties:
                  selfLink:
                    type: string
                    description: Cluster self link
                  endpoint:
                    type: string
                    description: Cluster endpoint
                  location:
                    type: string
                    description: Cluster location
                  nodes:
                    type: object
                    properties:
                      cidr:
                        type: string
                        description: Subnetwork cidr
                      tags:
                        type: array
                        description: Network tags to apply to node pools
                        items:
                          type: string
                  pods:
                    type: object
                    properties:
                      cidr:
                        type: string
                        description: Cluster pods cidr
                  services:
                    type: object
                    properties:
                      cidr:
                        type: string
                        description: Cluster services cidr