---
apiVersion: gcp.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
  namespace: crossplane-system
spec:
  credentials:
    secretRef:
      name: bradw
      namespace: bradw
      key: credentials
  projectID: bradw-nextgen-devops