---
apiVersion: platform.projectx.mavenwave.dev/v1alpha1
kind: ControlPlaneClaim
metadata:
  name: controlplane
  namespace: a-team
spec:
  compositionSelector:
    matchLabels:
      provider: gcp
  writeConnectionSecretToRef:
    name: a-team-controlplane
  parameters:
    platform:
      version: latest
    google:
      project:
        id: bradw-nextgen-devops
        number: "809429613600"
      network:
        nodes:
          cidr: 10.0.0.0/24
        pods:
          cidr: 10.1.0.0/16
        services:
          cidr: 10.2.0.0/20
      cluster:
        identity:
          source: Secret
          secretRef:
            name: gcp-default
      crossplane:
        serviceAccount:
          email: crossplane@bradw-nextgen-devops.iam.gserviceaccount.com