---
apiVersion: platform.projectx.mavenwave.dev/v1alpha1
kind: ControlPlaneClaim
metadata:
  name: demo
  namespace: a-team
spec:
  compositionSelector:
    matchLabels:
      provider: gcp
  writeConnectionSecretToRef:
    name: a-team-demo
  parameters:
    platform:
      version: latest
    google:
      project:
        id: bradw-nextgen-devops
        number: "809429613600"
      crossplaneServiceAccountEmail: crossplane@bradw-nextgen-devops.iam.gserviceaccount.com
    nodeCidr: 10.0.0.0/24
    podCidr: 10.1.0.0/16
    serviceCidr: 10.2.0.0/20
    identity:
      source: Secret
      secretRefName: k8s-default
     