---
apiVersion: platform.projectx.mavenwave.dev/v1alpha1
kind: ControlPlane
metadata:
  name: cp-gke
spec:
  compositionSelector:
    matchLabels:
      provider: gcp
  parameters:
    platform: {}
    google: {}