apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: crossplane-system

resources:
- tenant.yaml

configMapGenerator:
- name: tenant
  env: config.properties

replacements:
- source:
    kind: ConfigMap
    name: tenant
    fieldPath: data.PROJECTID
  targets:
  - select:
      kind: Tenant
    fieldPaths:
    - spec.parameters.google.project.projectId
- source:
    kind: ConfigMap
    name: tenant
    fieldPath: data.FOLDERID
  targets:
  - select:
      kind: Tenant
    fieldPaths:
    - spec.parameters.google.project.folderId