apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/kind/deploy.yaml
# - github.com/kubernetes/ingress-nginx/deploy/static/provider/kind?ref=ingress-nginx-3.15.2

patchesJson6902:
- target:
    version: v1
    kind: Deployment
    name: ingress-nginx-controller
  path: add-args.yaml