name: Crossplane Package

on:
  push:
    paths-ignore:
    - '**.md'
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:
    paths-ignore:
    - '**.md'
    branches:
      - 'main'

env:
  REGISTRY: ghcr.io
  IMAGE: ${{ github.repository }}

jobs:
  package:
    runs-on: ubuntu-latest
    outputs:
      tags: ${{steps.split-tags.outputs.tags}}
    steps:
    - uses: actions/checkout@v3

    - name: Install Crossplane Plugin
      id: crossplane-plugin
      run: |
        cd /usr/local/bin
        if [ ! -f  kubectl-crossplane ]; then
          curl -sL https://raw.githubusercontent.com/crossplane/crossplane/master/install.sh | sudo sh
        fi

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
     
    - name: Log in to the Container registry
      uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE }}
        sep-tags: ","
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=sha

    - name: Split Docker Tags
      id: split-tags
      run: |
        echo "::set-output name=tags:: $(echo ${{steps.meta.outputs.tags}} | sed 's/,/ /g')"

    - name: Build Crossplane Packages
      run: |
        for i in ${{steps.split-tags.outputs.tags}}; do make push CONTAINER=$i; done