name: Crossplane Package

on:
  push:
    paths-ignore:
    - '**.md'
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:
    paths-ignore:
    - '**.md'
    branches:
      - 'main'

env:
  REGISTRY: ghcr.io
  IMAGE: ${{ github.repository }}

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
    - run: |
        cd /usr/local/bin
        if [ ! -f  kubectl-crossplane ]; then
          curl -sL https://raw.githubusercontent.com/crossplane/crossplane/master/install.sh | sudo sh
        fi

    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
     
    - name: Log in to the Container registry
      uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: PrepareReg Names
      run: |
        echo IMAGE=$(echo ${{ env.IMAGE }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE }}
        sep-tags: ","
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=sha
    
    - name: Build Crossplane Packages
      run: |
        cd package
        kubectl crossplane build configuration
        for i in $(echo ${{ steps.meta.outputs.tags }} | tr "," " "); do kubectl crossplane push configuration $i; done