name: build-compositions
on:
  pull_request:
    branches:    
    - main
jobs:
  build:
    strategy:
      matrix: 
        composition:
        - gcp-secure
    runs-on: ubuntu-latest
    container:
      image: k8s.gcr.io/kustomize/kustomize:v3.8.7
    steps:
     - uses: actions/checkout@v3
     - run: |
        kustomize src/compositions/${{ matrix.compositions }} > package/${{ matrix.compositions }}-compositions.yaml
