apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xnats.gcp.projectx.mavenwave.dev
spec:
  group: gcp.projectx.mavenwave.dev
  names:
    kind: XNat
    plural: xnats
  claimNames:
    kind: Nat
    plural: nats
  defaultCompositionRef:
    name: projectx-gcp-nat
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  providerConfigRef:
                    type: object
                    properties:
                      name:
                        type: string
                        description: Provider config for resources
                    required:
                    - name
                  id:
                    type: string
                    description: Referenceable id for resources
                  network:
                    type: object
                    properties:
                      id:
                        type: string
                        description: ID of VPC to attach
                  description:
                    type: string
                    description: Description on router
                  region:
                    type: string
                    enum:
                    - us-central
                    - us-east
                    - us-west
                    default: us-central
                    description: Subnet region
                required:
                - providerConfigRef
                - id
            required:
            - parameters
                  
          status:
            type: object
            properties: